### ISSUE TITLE
Not working at all.

### ISSUE THREAD

**Issue by DSMN2682** [ekaj2/UltiMaze#4]
I am installing the add-on from the .zip file as directed and then checking the box to enable the add-on.  After that there is no option to use the add-on tool anywhere that I can find.  Either it is not installing properly or is in a sub-menu somewhere but I tried menu and operator search with no luck on finding or using this tool.  Any help would be greatly appreciated.  I tried installing this on both Blender 2.83 and 2.91.

**Comment by ekaj2** [comment]
This addon does not support Blender 2.8/2.9. Please see [here](https://github.com/ekaj2/UltiMaze/blob/master/__init__.py#L56) and [here](https://blendermarket.com/products/ultimaze-pro):

<img width="1162" alt="Screen Shot 2021-04-14 at 8 07 16 AM" src="https://user-images.githubusercontent.com/20780097/114707691-8446ff80-9cf8-11eb-9051-d7f4ac213e18.png">

If you need to use a newer version of Blender, then you will have to build the maze in 2.7x and then export/import it into 2.8 or 2.9. I'm sorry for the inconvenience, but I have not had enough interest in the addon to make it worth updating to a newer version of Blender.
